# Generated by Django 4.1.7 on 2023-06-17 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_persona_persona_fecha_nacimineto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cola',
            name='cola_estado',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cola',
            name='cola_fecha_hora_ingreso',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cola',
            name='usuario_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]

