# Generated by Django 4.1.7 on 2023-06-17 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_cola_cola_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cola',
            name='nivel_prioridad_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.nivelprioridad'),
        ),
        migrations.AlterField(
            model_name='cola',
            name='persona_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.persona'),
        ),
        migrations.AlterField(
            model_name='cola',
            name='servicio_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.servicio'),
        ),
    ]