# Generated by Django 4.1.7 on 2023-06-20 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_cola_nivel_prioridad_id_alter_cola_persona_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cola',
            name='cola_fecha_hora_atencion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cola',
            name='cola_fecha_hora_ingreso',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cola',
            name='cola_fecha_hora_salida',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
